#!/bin/sh
#
# cvpfinder4j ver. 1.1
# (C) 2022-2023 Hirohisa Aman <aman@ehime-u.ac.jp>
#
####################################################################
# TODO:
# Download javaparser from https://github.com/javaparser/javaparser
# and put it into "lib" dir.
# Edit the following setting if you get a different version.
JAVAPARSER=javaparser-core-3.24.2.jar
####################################################################

STRING_SIM_THRESHOLD=0.75
SEMANTIC_SIM_THRESHOLD=0.96

BASE_DIR=$(cd $(dirname $0) && pwd)
LIB_DIR=${BASE_DIR}/lib
REPORT_DIR=${BASE_DIR}/report

VAR_TABLE=${REPORT_DIR}/variable_table.txt
CANDIDATE_SET=${REPORT_DIR}/variable_pairs.txt
REPORT_FILE=${REPORT_DIR}/report.csv

if [ ! -e ${LIB_DIR}/$JAVAPARSER ]; then
  echo "*** ERROR ***"
  echo "${LIB_DIR}/$JAVAPARSER not found!"
  exit
fi

java -cp ${LIB_DIR}/JavaVariableExtractor.jar:${LIB_DIR}/$JAVAPARSER org.computer.aman.metrics.util.var_scope.Main $* | cut -f1,4-7 > ${VAR_TABLE}

python ${LIB_DIR}/comp_var_extractor.py ${LIB_DIR}/addtional_words.txt < ${VAR_TABLE} > ${VAR_TABLE}.comp
if [ $(wc -l ${VAR_TABLE}.comp | cut -f1 -d' ') -eq 1 ]; then
  echo "No variable with compound name found"
  rm -f ${VAR_TABLE}.comp
  exit
fi

python ${LIB_DIR}/var_pair_extractor.py < ${VAR_TABLE}.comp > $CANDIDATE_SET
rm -f ${VAR_TABLE}.comp
if [ $(wc -l $CANDIDATE_SET | cut -f1 -d' ') -eq 1 ]; then
  echo "No variable pair found"
  exit
fi

echo -n "Computing string similarity ... "
python ${LIB_DIR}/compute_Levenshtein_similarity.py < $CANDIDATE_SET > $CANDIDATE_SET.str
echo "done."
echo -n "Computing semantic similarity ... "
python ${LIB_DIR}/compute_semantic_similarity.py ${LIB_DIR}/doc2vec4java.model < $CANDIDATE_SET > $CANDIDATE_SET.sem
echo "done."

echo ""
python ${LIB_DIR}/print_report.py $STRING_SIM_THRESHOLD $SEMANTIC_SIM_THRESHOLD $CANDIDATE_SET.str $CANDIDATE_SET.sem $REPORT_FILE
rm -f $CANDIDATE_SET.str $CANDIDATE_SET.sem
